### ISSUE TITLE
Investigate moving this into the google/protobuf project instead

### ISSUE THREAD

**Issue by thomasvl** [apple/swift-protobuf-test-conformance#1]
Go protobuf support also doesn't live in google/protobuf, but to help get better visibility into regressions/issues/etc.; https://github.com/google/protobuf/pull/2084 is in flight to get the conformance tests run more frequently.  It might make sense to do the same things for Swift.

**Comment by tbkka** [comment]
There are a couple of related questions here:

   1. Does it make sense to move the conformance plugin into the same repo?  (Instead of having it in a separate swift-protobuf-test-conformance repo?)
   2. Can we make google/protobuf/conformance easier to use?  (For example, google/protobuf/conformance doesn't support out-of-tree builds, which might make it simpler.)

Of course, once we have CI support, we can explore running the conformance tests on every change.

**Comment by tbkka** [comment]
Rethinking my previous comment ...

An alternative would be to make google/protobuf/conformance easier to use by out-of-tree conformance plugins.   For example, the conformance host could be installed alongside protoc (e.g., as protoc-conformance).  Then protoc plugins could use it more easily.

**Comment by thomasvl** [comment]
The catch here is the conformance proto itself.  That really has to remain in sync between the test runner and the thing being tested.  That I think why the go one is headed down the path of having the language specific part live in google/protobuf, that way it is easier to keep in sync with the required support.

**Comment by thomasvl** [comment]
Closing this off as it got moved into the swift-protobuf instead.
